Revert "[FIX] AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'"
This reverts commit e1c371c17fdbeba2674a72b9f62dbf5067eaebf3.